# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout 
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - run:
          name: Build
          command: npm build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: build
          prefix: build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependecies
          command: npm install
      - run:
          name: Test
          command: npm run test -- --coverage


workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
